/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseFooter: typeof import('./src/components/BaseFooter.vue')['default']
    BaseHeader: typeof import('./src/components/BaseHeader.vue')['default']
    BaseLnb: typeof import('./src/components/BaseLnb.vue')['default']
    Career: typeof import('./src/components/resume/Career.vue')['default']
    Certificate: typeof import('./src/components/resume/Certificate.vue')['default']
    Certification: typeof import('./src/components/resume/Certification.vue')['default']
    DataTable: typeof import('./src/components/common/DataTable.vue')['default']
    Edu: typeof import('./src/components/resume/Edu.vue')['default']
    Education: typeof import('./src/components/resume/Education.vue')['default']
    FormDatepicker: typeof import('./src/components/common/FormDatepicker.vue')['default']
    FormSelect: typeof import('./src/components/common/FormSelect.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon: typeof import('./src/components/common/Icon.vue')['default']
    Information: typeof import('./src/components/resume/Information.vue')['default']
    MenuSearch: typeof import('./src/components/layout/MenuSearch.vue')['default']
    ModalDialog: typeof import('./src/components/common/modalDialog.vue')['default']
    PageSection: typeof import('./src/components/layout/PageSection.vue')['default']
    PageTitle: typeof import('./src/components/layout/PageTitle.vue')['default']
    Project: typeof import('./src/components/projects/Project.vue')['default']
    Projects: typeof import('./src/components/Projects.vue')['default']
    Resume: typeof import('./src/components/Resume.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stack: typeof import('./src/components/resume/Stack.vue')['default']
    Til: typeof import('./src/components/Til.vue')['default']
    TilMain: typeof import('./src/components/TilMain.vue')['default']
    TitleBar: typeof import('./src/components/common/TitleBar.vue')['default']
  }
}
